-- Environment
require('environment')

require('plugins')
require('lv-globals')
require('lv-utils')
require('lv-autocommands')
require('settings')
if io.open(CONFIG_PATH .. '/lv-settings.lua', 'r') then
	vim.cmd('luafile ' .. CONFIG_PATH .. '/lv-settings.lua')
end
require('keymappings')
require('colorscheme')
require('lv-galaxyline')
require('lv-comment')
require('lv-compe')
require('lv-barbar')
require('lv-dashboard')
require('lv-telescope')
require('lv-gitsigns')
require('lv-nvimtree')
require('lv-treesitter')
require('lv-autopairs')
require('lv-rnvimr')
require('lv-which-key')

-- James
require('lv-trim')

-- TODO is there a way to do this without vimscript
vim.cmd('source ' .. lv_base .. '/vimscript/functions.vim')

-- LSP
require('lsp')
require('lsp.clangd')
require('lsp.php-ls')
require('lsp.dart-ls')
require('lsp.lua-ls')
require('lsp.bash-ls')
require('lsp.go-ls')
require('lsp.js-ts-ls')
require('lsp.python-ls')
require('lsp.rust-ls')
require('lsp.json-ls')
require('lsp.yaml-ls')
require('lsp.terraform-ls')
require('lsp.vim-ls')
require('lsp.graphql-ls')
require('lsp.docker-ls')
require('lsp.html-ls')
require('lsp.css-ls')
require('lsp.emmet-ls')
require('lsp.efm-general-ls')
require('lsp.latex-ls')
require('lsp.svelte-ls')
-- require('lsp.tailwindcss-ls')
require('lsp.ruby-ls')
require('lsp.kotlin-ls')
require('lsp.vue-ls')
require('lsp.angular-ls')

